{% set name = "gemmi" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/project-gemmi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1e5a4e4351e5860d70c3aa4ebc762b3f098160dad936e1775bd1d165575516bf

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
  host:
    - pybind11
    - python
    - setuptools
    - zlib
  run:
    - python

test:
  commands:
    - gemmi --help
    - python -m gemmi-examples
    - pip check
  imports:
    - gemmi
  requires:
    - pip

about:
  home: https://project-gemmi.github.io/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Macromolecular crystallography library and utilities.
  doc_url: https://gemmi.readthedocs.io/
  dev_url: https://github.com/project-gemmi/gemmi

extra:
  recipe-maintainers:
    - anthchirp
    - mcs07
