{% set name = "gemmi" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/project-gemmi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 839fe4ad10bc0d9586992be243e0179f7d8d8ce794540bacece221ddf9a6710e

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [linux]
    - ninja  # [win]
  host:
    - pybind11
    - python
    - setuptools
    - zlib
  run:
    - python

test:
  commands:
    - gemmi --help
    - python -m gemmi-examples
    - pip check
  imports:
    - gemmi
  requires:
    - pip

about:
  home: https://project-gemmi.github.io/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Macromolecular crystallography library and utilities.
  doc_url: https://gemmi.readthedocs.io/
  dev_url: https://github.com/project-gemmi/gemmi

extra:
  recipe-maintainers:
    - anthchirp
    - mcs07
